name: entrapprendre_content
description: Validation et publication des contenus Entr'Apprendre.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  archive: ^4.0.9
  crypto: ^3.0.7
  path: ^1.9.1
